Question 1: Given a set my_set = {10, 20, 30, 40, 50}, how can you access the element 30 from the set? Write a Python program to achieve this.

In [ ]:
my_set ={10,20,30,40,50}
my_set.remove(10)
my_set.remove(20)
my_set.remove(50)
my_set.remove(40)
my_set

{30}

Question 2: Suppose you have a set my_set = {15, 25, 35, 45, 55}, how can you perform slicing on a set? Write a Python program to demonstrate.

In [ ]:

my_set={15,25,35,45,55}
my_set=slice(15,55)
my_set

slice(15, 55, None)


Question 3: Given two sets set1 = {1, 2, 3} and set2 = {4, 5, 6}, how can you perform union operation on them? Write a Python program to achieve this.

In [ ]:
set1 = {1, 2, 3}
set2 = {4, 5, 6}
set1.union(set2)

{1, 2, 3, 4, 5, 6}

Question 4: Suppose you have a set my_set = {1, 2, 3, {4, 5, 6}}, how can you access the nested set {4, 5, 6} from it? Write a Python program to achieve this.

In [13]:
my_set = {1, 2, 3, frozenset({4, 5, 6})}
for element in my_set:
  if isinstance(element,frozenset):  # Check if the element is a set
    nested_set = element
    break  # Exit the loop once the nested set is found

print(nested_set)

frozenset({4, 5, 6})

In [14]:
my_set = {1, 2, 3,(4, 5, 6)}
for element in my_set:
  if isinstance(element,tuple):  # Check if the element is a set
    nested_set = element
    break  # Exit the loop once the nested set is found

print(nested_set)

(4, 5, 6)

Question 5: Given a set my_set = {1, 2, 3, 4, 5}, how can you convert it to a list? Write a Python program to achieve this.

In [ ]:
my_set ={1,2,3,4,5}
list(my_set)

[1, 2, 3, 4, 5]